# Generated by Django 2.2.1 on 2020-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curated_category_type', models.CharField(choices=[('app_type', 'App Type'), ('biology', 'Biology'), ('data', 'Data')], max_length=255)),
                ('type_description', models.CharField(blank=True, max_length=500)),
                ('curated_category', models.CharField(max_length=255, unique=True)),
                ('curated_category_description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'curated_categories',
                'ordering': ['curated_category_type'],
            },
        ),
        migrations.CreateModel(
            name='CuratedCategoriesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=True, to='apps.App')),
                ('curated_categories', models.ManyToManyField(blank=True, to='curated_categories.CuratedCategory')),
            ],
            options={
                'verbose_name_plural': 'curated_categories_mapping',
                'ordering': ['app'],
            },
        ),
    ]
