# Generated by Django 2.1.7 on 2019-03-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadsByGeoLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.App')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('ip4addr', models.PositiveIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_download_stats', to='apps.Release')),
            ],
        ),
        migrations.CreateModel(
            name='GeoLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDownloadsByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Release')),
            ],
        ),
        migrations.AddField(
            model_name='appdownloadsbygeoloc',
            name='geoloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.GeoLoc'),
        ),
    ]
