# Generated by Django 2.1.7 on 2019-03-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=127)),
                ('version', models.CharField(max_length=31)),
                ('cy_works_with', models.CharField(max_length=31)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('release_file', models.FileField(upload_to='pending_releases')),
                ('javadocs_jar_file', models.FileField(blank=True, null=True, upload_to='pending_releases')),
                ('pom_xml_file', models.FileField(blank=True, null=True, upload_to='pending_releases')),
                ('dependencies', models.ManyToManyField(blank=True, null=True, related_name='_apppending_dependencies_+', to='apps.Release')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
